/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sn.ugb.ipsl.guiiproject;

import javax.swing.JOptionPane;
import sn.ugb.ipsl.entite.Etudiant;
import sn.ugb.ipsl.service.EtudiantServiceImp;

/**
 *
 * @author user
 */
public class AddEtudiant extends javax.swing.JPanel {

    EtudiantServiceImp etudiantservice = new EtudiantServiceImp();

    /**
     * Creates new form AddEtudiant
     */
    public AddEtudiant() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        DateTextField5 = new javax.swing.JTextField();
        IdTextField12 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        PrenomTextField6 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        NomTextField7 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        NiveauComboBox1 = new javax.swing.JComboBox<>();
        FiliereComboBox2 = new javax.swing.JComboBox<>();
        saveToggleButton1 = new javax.swing.JToggleButton();
        annulerToggleButton1 = new javax.swing.JToggleButton();

        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("ajout etudiant");
        add(jLabel1);
        jLabel1.setBounds(240, 20, 170, 29);

        jLabel2.setText("Filiere:");
        add(jLabel2);
        jLabel2.setBounds(10, 380, 60, 14);

        DateTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateTextField5ActionPerformed(evt);
            }
        });
        add(DateTextField5);
        DateTextField5.setBounds(70, 310, 140, 30);

        IdTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdTextField12ActionPerformed(evt);
            }
        });
        add(IdTextField12);
        IdTextField12.setBounds(60, 100, 50, 20);

        jLabel3.setText("ID:");
        add(jLabel3);
        jLabel3.setBounds(20, 100, 20, 14);

        jLabel4.setText("Prenom:");
        add(jLabel4);
        jLabel4.setBounds(10, 150, 40, 14);

        jLabel5.setText("Prenom:");
        add(jLabel5);
        jLabel5.setBounds(10, 150, 40, 14);

        PrenomTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrenomTextField6ActionPerformed(evt);
            }
        });
        add(PrenomTextField6);
        PrenomTextField6.setBounds(60, 140, 120, 30);

        jLabel6.setText("Nom:");
        add(jLabel6);
        jLabel6.setBounds(10, 200, 40, 14);

        NomTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomTextField7ActionPerformed(evt);
            }
        });
        add(NomTextField7);
        NomTextField7.setBounds(60, 190, 130, 30);

        jLabel7.setText("Niveau:");
        add(jLabel7);
        jLabel7.setBounds(10, 260, 40, 14);

        jLabel8.setText("Date-Naiss:");
        add(jLabel8);
        jLabel8.setBounds(10, 320, 60, 14);

        NiveauComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "L1", "L2", "L3", "M1","M2" }));
        NiveauComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NiveauComboBox1ActionPerformed(evt);
            }
        });
        add(NiveauComboBox1);
        NiveauComboBox1.setBounds(60, 252, 150, 30);

        FiliereComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Genie info", "reseaux-telecom", "genie civil", "Electro-meca" }));
        add(FiliereComboBox2);
        FiliereComboBox2.setBounds(70, 372, 150, 30);

        saveToggleButton1.setText("Enregistrer");
        saveToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveToggleButton1ActionPerformed(evt);
            }
        });
        add(saveToggleButton1);
        saveToggleButton1.setBounds(450, 430, 85, 23);

        annulerToggleButton1.setText("annuler");
        annulerToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerToggleButton1ActionPerformed(evt);
            }
        });
        add(annulerToggleButton1);
        annulerToggleButton1.setBounds(330, 430, 69, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void DateTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DateTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DateTextField5ActionPerformed

    private void IdTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdTextField12ActionPerformed

    private void PrenomTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrenomTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrenomTextField6ActionPerformed

    private void NomTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomTextField7ActionPerformed

    private void NiveauComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NiveauComboBox1ActionPerformed

    }//GEN-LAST:event_NiveauComboBox1ActionPerformed

    private void saveToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveToggleButton1ActionPerformed
        String idString = IdTextField12.getText();
        String prenom = PrenomTextField6.getText();
        String nom = NomTextField7.getText();
         String datenaiss = DateTextField5.getText();
        String niveau = NiveauComboBox1.getSelectedItem().toString();
        String filiere = FiliereComboBox2.getSelectedItem().toString();
       

        Integer id = Integer.parseInt(idString);
        Etudiant e = new Etudiant();
        e.setId(id);
        e.setPrenom(prenom);
        e.setNom(nom);
        e.setDatenaiss(datenaiss);
        e.setNiveau(niveau);
        e.setFiliere(filiere);
        

        if (prenom == null || prenom.isBlank()) {
            JOptionPane.showMessageDialog(this, "le prenom est obligatoire", "error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        etudiantservice.add(e);
        JOptionPane.showMessageDialog(this, " ajouter etudiant", "", JOptionPane.INFORMATION_MESSAGE);
        PrenomTextField6.setText("");

    }//GEN-LAST:event_saveToggleButton1ActionPerformed

    private void annulerToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annulerToggleButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_annulerToggleButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DateTextField5;
    private javax.swing.JComboBox<String> FiliereComboBox2;
    private javax.swing.JTextField IdTextField12;
    private javax.swing.JComboBox<String> NiveauComboBox1;
    private javax.swing.JTextField NomTextField7;
    private javax.swing.JTextField PrenomTextField6;
    private javax.swing.JToggleButton annulerToggleButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JToggleButton saveToggleButton1;
    // End of variables declaration//GEN-END:variables
}
