/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sn.ugb.ipsl.guiiproject;

import javax.swing.JOptionPane;
import sn.ugb.ipsl.service.FiliereServiceImp;

/**
 *
 * @author user
 */
public class deletefil extends javax.swing.JPanel {

    FiliereServiceImp filiereservice = new FiliereServiceImp();
    
    /**
     * Creates new form deletefil
     */
    public deletefil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        filiere = new javax.swing.JTextField();
        deleteToggleButton = new javax.swing.JToggleButton();

        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("delete filiere");
        add(jLabel1);
        jLabel1.setBounds(166, 11, 147, 31);

        filiere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filiereActionPerformed(evt);
            }
        });
        add(filiere);
        filiere.setBounds(166, 60, 147, 33);

        deleteToggleButton.setText("Supprimer");
        deleteToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteToggleButtonActionPerformed(evt);
            }
        });
        add(deleteToggleButton);
        deleteToggleButton.setBounds(438, 217, 81, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void filiereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filiereActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filiereActionPerformed

    private void deleteToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteToggleButtonActionPerformed
       String fil=filiere.getText();
        if (fil==null || fil.isBlank()) {
           JOptionPane.showMessageDialog(this, "ce champ est obligatoire", "error", JOptionPane.ERROR_MESSAGE);
           return;
        }
        filiereservice.delete(fil);
         JOptionPane.showMessageDialog(this, "la filiere est supprimer", "", JOptionPane.INFORMATION_MESSAGE);
        filiere.setText("");
    }//GEN-LAST:event_deleteToggleButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton deleteToggleButton;
    private javax.swing.JTextField filiere;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
